name: 🚀 Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Install dependencies & Build
        run: |
          npm install
          npm run build

      - name: 🚀 Deploy App via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          ARGS: "-rlgoDvc --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: "root"
          TARGET: "/var/www/kermi-static"
          EXCLUDE: "/.git, /.github, /node_modules"
